version: "2"
services:
  dev:
    build: .
    image: keboola/google-sheets-writer
    volumes:
      - .:/code
    working_dir: /code
    command: bash
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      GOOGLE_DRIVE_FOLDER: ${GOOGLE_DRIVE_FOLDER}
      GOOGLE_DRIVE_TEAM_FOLDER: ${GOOGLE_DRIVE_TEAM_FOLDER}
      KBC_LOGGER_ADDR: log-server
      KBC_LOGGER_PORT: 12202
    links:
      - log-server

  tests:
    build: .
    image: keboola/google-sheets-writer
    working_dir: /code
    command: composer ci
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      REFRESH_TOKEN: ${REFRESH_TOKEN}
      GOOGLE_DRIVE_FOLDER: ${GOOGLE_DRIVE_FOLDER}
      GOOGLE_DRIVE_TEAM_FOLDER: ${GOOGLE_DRIVE_TEAM_FOLDER}
      KBC_LOGGER_ADDR: log-server
      KBC_LOGGER_PORT: 12202
    links:
      - log-server

  log-server:
    image: "quay.io/keboola/docs-example-logging-mock-server:master"
    ports:
      - 12202:12202/tcp
    environment:
      SERVER_TYPE: tcp
